spring:
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:true}
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 512
      minimum-idle: 16
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: SpringJpaHikari
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
      jakarta:
        persistence:
          sharedCache:
            mode: NONE

server:
  port: 8080

logging:
  level:
    root: WARN
