httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  virtualThreadsEnabled = true
}


db {
  jdbcUrl = ${POSTGRES_JDBC_URL}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  poolName = kora
  minIdle = 48
  maxPoolSize = 48
  initializationFailTimeout = "10s"
  dsProperties {
    "tcpKeepAlive": "true",
    "preparedStatementCacheQueries": "512",
    "preparedStatementCacheSizeMiB": "16"
    "prepareThreshold": "1"
    "loggerLevel": "OFF"
    "sslmode": "disable"
    "disableColumnSanitiser": "true"
  }
}
