plugins {
    id "java"
    id "org.springframework.boot" version "$springBootVersion"
    id "io.spring.dependency-management" version "1.1.7"
    id "gg.jte.gradle" version "3.2.3"
}

version = springBootVersion

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    runtimeOnly "org.slf4j:slf4j-nop:2.0.17"

    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.boot:spring-boot-starter-data-r2dbc"
    implementation "org.postgresql:r2dbc-postgresql:1.0.7.RELEASE"
    implementation "gg.jte:jte:3.2.3"
    implementation "gg.jte:jte-runtime:3.2.3"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-webflux-test"
    testImplementation "io.projectreactor:reactor-test"
    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:postgresql:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "build", "generated", "jte")
    sourceSets.main.java.srcDirs += "build/generated/jte"
    contentType = gg.jte.ContentType.Html
}

compileJava.dependsOn tasks.generateJte

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs += "-parameters"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.named("bootJar") {
    archiveFileName = "${project.name}.jar"
}
