server:
  host: 0.0.0.0
  port: 8080
  virtual-threads:
    enabled: ${VIRTUAL_THREADS_ENABLED:true}
  backlog: 8192
  write-queue-length: 8192
  smart-async-writes: true
  connection-options:
    tcp-no-delay: true
  protocols:
    "http_1_1":
      validate-request-headers: true
      validate-response-headers: true
      validate-path: true
      recv-log: false
      send-log: false

data:
  persistence-units:
    jakarta:
      - name: "@default"
        provider-class-name: "org.hibernate.jpa.HibernatePersistenceProvider"
        properties:
          jakarta.persistence.jdbc.driver: "org.postgresql.Driver"
          jakarta.persistence.jdbc.url: jdbc:postgresql://localhost:5432/postgres
          jakarta.persistence.jdbc.user: postgres
          jakarta.persistence.jdbc.password: postgres
          hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
          hibernate.hikari.autoCommit: false
          hibernate.connection.provider_disables_autocommit: true
          hibernate.hikari.maximumPoolSize: 512
          hibernate.hikari.dataSource.prepareThreshold: 1
          hibernate.hikari.dataSource.preparedStatementCacheQueries: 512
          hibernate.hikari.dataSource.preparedStatementCacheSizeMiB: 16
          hibernate.hikari.dataSource.loggerLevel: OFF
          hibernate.hikari.dataSource.sslmode: disable
          hibernate.hikari.dataSource.tcpKeepAlive: true
          hibernate.hikari.dataSource.disableColumnSanitiser: true
          hibernate.show_sql: false
          hibernate.format_sql: false
          hibernate.generate_statistics: false
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          jakarta.persistence.sharedCache.mode: NONE

logging:
  level: WARNING
