plugins {
    id "java"
    id "application"
    id "io.micronaut.application" version "5.0.2"
    id "io.micronaut.aot" version "5.0.2"
    id "gg.jte.gradle" version "3.2.3"
}

version = micronautVersion
group = "io.micronaut.benchmark"

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("io.micronaut.benchmark.*")
    }
}

dependencies {
    annotationProcessor "io.micronaut.serde:micronaut-serde-processor"
    annotationProcessor "io.micronaut.data:micronaut-data-processor"

    runtimeOnly "ch.qos.logback:logback-classic"

    implementation "io.micronaut.serde:micronaut-serde-jackson"
    implementation "io.micronaut.data:micronaut-data-jdbc"
    implementation "io.micronaut.sql:micronaut-jdbc-hikari"
    implementation "org.postgresql:postgresql"
    implementation "gg.jte:jte:3.2.3"
    implementation "io.micronaut:micronaut-http-server-netty"

    testImplementation "org.testcontainers:testcontainers:1.20.1"
    testImplementation "org.testcontainers:postgresql:1.20.1"
    testImplementation "org.testcontainers:junit-jupiter:1.20.1"
}

application {
    mainClass.set("io.micronaut.benchmark.Application")
    applicationDefaultJvmArgs = ["-Dfile.encoding=UTF-8"]
}

distTar {
    archiveFileName = "application.tar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "build", "generated", "jte")
    sourceSets.main.java.srcDirs += "build/generated/jte"
    contentType = gg.jte.ContentType.Html
}

compileJava.dependsOn tasks.generateJte
