#!/usr/bin/env bash

./tfb \
  --test \
  quarkus \
  quarkus-vertx \
  fair-kora1-jdbc \
  fair-kora1-jdbc-vt \
  fair-kora1-vertx-repository-suspend \
  fair-kora1-jdbc-repository-suspend \
  fair-kora2-jdbc \
  fair-kora2-jdbc-repository-kotlin \
  fair-ktor-netty-jdbc \
  fair-ktor-cio-jdbc \
  fair-helidon-mp-jdbc-client \
  fair-helidon-mp-jpa-repository \
  fair-micronaut-jdbc-repository \
  fair-micronaut-jpa-repository \
  fair-micronaut-jpa-data-reactive \
  fair-micronaut-r2dbc-data-reactive \
  fair-quarkus-jooq \
  fair-quarkus-jpa-ac \
  fair-quarkus-jpa-ac-reactive \
  fair-quarkus-jpa-repository \
  fair-quarkus-jpa-repository-reactive \
  fair-spring-jdbc-repository \
  fair-spring-jdbc-template \
  fair-spring-jpa-repository \
  fair-spring-r2dbc-repository-reactive \
  fair-spring-r2dbc-client-reactive \
  fair-vertx-pg-client \
  ntex-db \
  ntex-db-neon \
  micronaut \
  micronaut-graalvm \
  micronaut-jdbc \
  micronaut-jdbc-graalvm \
  micronaut-data-jdbc \
  micronaut-data-jdbc-graalvm \
  micronaut-loom-fjp \
  micronaut-loom-on-netty \
  micronaut-r2dbc \
  micronaut-r2dbc-graalvm \
  quarkus \
  quarkus-hibernate-reactive \
  quarkus-reactive-routes-pgclient \
  quarkus-vertx \
  spring \
  spring-jooq \
  spring-data-jdbc \
  spring-webflux \
  undertow-postgresql \
  --type all \
  --concurrency-levels 16 32 64 128 \
  --pipeline-concurrency-levels 256 1024 4096 \
  -m benchmark
