kora1Version=1.2.18
kora2Version=2.0.0.RC1
micronautVersion=5.0.4
quarkusVersion=3.37.2
springBootVersion=4.1.0
helidonVersion=4.5.0
vertxVersion=5.0.5
#
#
#
postgresHost=localhost
postgresPort=5432
postgresDatabase=postgres
postgresUser=postgres
postgresPassword=postgres
#
#
#
org.gradle.jvmargs=-Dfile.encoding=UTF-8
