pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'fair-benchmark'

include 'java-kora-jdbc'
include 'java-quarkus-jpa-dao'
include 'java-quarkus-jpa-repository'
include 'java-micronaut-jdbc-data'
include 'java-micronaut-jpa-data'
include 'java-spring-jdbc-data'
include 'java-spring-jdbc-template'
include 'java-spring-jpa-data'
include 'java-spring-r2dbc-data-reactive'
include 'java-helidon-jdbc-nima'
