server:
  host: 0.0.0.0
  port: 8080
  virtual-threads:
    enabled: ${VIRTUAL_THREADS_ENABLED:true}
  backlog: 8192
  write-queue-length: 8192
  smart-async-writes: true
  connection-options:
    read-timeout: PT0S
    connect-timeout: PT0S
    tcp-no-delay: true
  protocols:
    "http_1_1":
      validate-request-headers: false
      validate-response-headers: false
      validate-path: false
      recv-log: false
      send-log: false

data:
  persistence-units:
    jakarta:
      - name: "@default"
        provider-class-name: "org.hibernate.jpa.HibernatePersistenceProvider"
        properties:
          jakarta.persistence.jdbc.driver: "org.postgresql.Driver"
          jakarta.persistence.jdbc.url: ${POSTGRES_JDBC_URL:"jdbc:postgresql://localhost:5432/postgres"}
          jakarta.persistence.jdbc.user: ${POSTGRES_USER:postgres}
          jakarta.persistence.jdbc.password: ${POSTGRES_PASS:postgres}
          hibernate.connection.provider_disables_autocommit: true
          hibernate.hikari.maximumPoolSize: 64
          hibernate.hikari.dataSource.cachePrepStmts: true
          hibernate.hikari.dataSource.prepStmtCacheSize: 250
          hibernate.hikari.dataSource.prepStmtCacheSqlLimit: 2048
          hibernate.hikari.dataSource.ssl: false
          hibernate.hikari.dataSource.tcpKeepAlive: true
          hibernate.show_sql: false
          hibernate.format_sql: false
