
db {
  jdbcUrl = ${POSTGRES_JDBC_URL}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  poolName = korad
  maxPoolSize = 48
  minIdle = 8
  initializationFailTimeout = "10s"
  dsProperties {
      "loggerLevel": "OFF"
      "disableColumnSanitiser": "true"
  }
}

logging.level {
    "ru.tinkoff.kora.http.server.common.HttpServer" = "OFF"
    "ru.tinkoff.kora.database" = "off"
    "ru.tinkoff.kora.database.jdbc.test.query" = "off"
    "ru.tinkoff.kora.techempower.reactive.Application" = "debug"
    "ru.tinkoff.kora.techempower.loom.undertow.undertow.UndertowHttpServer" = "debug"
    "ru.tinkoff.kora.http.server.undertow.UndertowHttpServer" = "debug"
    "com.zaxxer.hikari" = "warn"
    "io.undertow.request" = "WARN"
}

pool {
  mode = "DEFAULT"
  mode = ${?POOL_MODE}
}
