httpServer {
  port = 8080
  telemetry {
      logging.enabled = false
      metrics.enabled = false
      tracing.enabled = false
  }
}

httpServer.system {
  port = 8085
  telemetry {
      logging.enabled = false
      metrics.enabled = false
      tracing.enabled = false
  }
}

jdbc {
  jdbcUrl = ${POSTGRES_JDBC_URL}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  minIdle = 16
  maxPoolSize = 512
  poolName = "kotlin-kora2-jdbc-repository"
  initializationFailTimeout = "10s"
  dsProperties {
    "preparedStatementCacheQueries": "512",
    "preparedStatementCacheSizeMiB": "16"
    "prepareThreshold": "1"
    "loggerLevel": "OFF"
    "sslmode": "disable"
    "disableColumnSanitiser": "true"
  }
  telemetry {
      logging.enabled = false
      metrics.enabled = false
      tracing.enabled = false
  }
}

logging.levels {
  "root": "WARN"
}
