plugins {
    id "java"
    id "application"
    id "gg.jte.gradle" version "3.2.3"
}

version = helidonVersion

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    implementation "io.helidon.webserver:helidon-webserver:4.5.0"
    implementation "io.helidon.config:helidon-config-yaml:4.5.0"
    implementation "io.helidon.http.media:helidon-http-media-jsonp:4.5.0"
    implementation "io.helidon.dbclient:helidon-dbclient:4.5.0"
    implementation "io.helidon.dbclient:helidon-dbclient-jdbc:4.5.0"
    implementation "io.helidon.integrations.cdi:helidon-integrations-cdi-datasource-hikari:4.5.0"
    implementation "org.postgresql:postgresql:42.7.11"
    implementation "gg.jte:jte:3.2.3"

    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:postgresql:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "build", "generated", "jte")
    sourceSets.main.java.srcDirs += "build/generated/jte"
    contentType = gg.jte.ContentType.Html
}

compileJava.dependsOn tasks.generateJte
