quarkus:
  http:
    port: 8080
  virtual-threads:
    enabled: ${VIRTUAL_THREADS_ENABLED:false}
    provider: jdk
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: none
