plugins {
    id "java"
    id "application"
    alias(libs.plugins.jte)
}

version = libs.versions.vertx.get()

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    runtimeOnly(libs.slf4jNop)

    implementation(libs.vertxWeb)
    implementation(libs.vertxPgClient)
    implementation(libs.jteRuntime)

    testRuntimeOnly(libs.logbackClassic)
    testImplementation(libs.testcontainersTestcontainers)
    testImplementation(libs.testcontainersPostgresql)
    testImplementation(libs.testcontainersJunitJupiter)
    testImplementation(libs.postgresql)
    testImplementation(libs.junitJupiter)
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = layout.projectDirectory.dir("src/main/jte").asFile.toPath()
    targetDirectory = layout.buildDirectory.dir("generated/jte").get().asFile.toPath()
    contentType = gg.jte.ContentType.Html
}

sourceSets {
    main {
        java.srcDir(layout.buildDirectory.dir("generated/jte"))
    }
}

compileJava.dependsOn tasks.generateJte

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    dependsOn(tasks.named("distTar"))
}

application {
    applicationName = "application"
    mainClass.set("io.techempower.benchmark.vertx.Application")
    applicationDefaultJvmArgs = ["-Dfile.encoding=UTF-8"]
}

tasks.named("run") {
    environment([
            "POSTGRES_REACTIVE_URL"    : "postgresql://$postgresHost:$postgresPort/$postgresDatabase",
            "POSTGRES_USER"            : "$postgresUser",
            "POSTGRES_PASS"            : "$postgresPassword",
            "POSTGRES_PIPELINING_LIMIT": "1",
    ])
}

tasks.named("distTar") {
    archiveFileName = "application.tar"
}
