plugins {
    id "java"
    id "application"
    id "gg.jte.gradle" version "3.2.3"
}

version = kora2Version

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    annotationProcessor "io.koraframework:annotation-processors:$kora2Version"
    implementation platform("io.koraframework:kora-parent:$kora2Version")

    runtimeOnly "ch.qos.logback:logback-classic:1.5.18"

    implementation "io.koraframework:database-jdbc"
    implementation "io.koraframework:config-hocon"
    implementation "io.koraframework:json-common"
    implementation "io.koraframework:http-server-undertow"
    implementation "gg.jte:jte:3.2.3"
    implementation "org.postgresql:postgresql:42.7.11"
    implementation("io.undertow:undertow-core") {
        version { strictly("2.3.24.Final") }
    }
    implementation("org.jboss.threads:jboss-threads") {
        version { strictly("3.9.2") }
    }
    implementation("org.jboss.xnio:xnio-nio") {
        version { strictly("3.8.17.Final") }
    }

    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:postgresql:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
    testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "build", "generated", "jte")
    sourceSets.main.java.srcDirs += "build/generated/jte"
    contentType = gg.jte.ContentType.Html
}

sourceSets {
    main {
        java.srcDir(layout.buildDirectory.dir("generated/jte"))
    }
}

compileJava.dependsOn tasks.generateJte

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    dependsOn(tasks.named("distTar"))
}

application {
    applicationName = "application"
    mainClass = "io.techempower.benchmark.kora.Application"
    applicationDefaultJvmArgs = ["-Dfile.encoding=UTF-8"]
}

distTar {
    archiveFileName = "application.tar"
}
