plugins {
    id "java"
    id "application"
    id "gg.jte.gradle" version "3.2.3"
}

version = koraVersion

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

configurations {
    koraBom
    compileOnly.extendsFrom(koraBom)
    annotationProcessor.extendsFrom(koraBom)
    implementation.extendsFrom(koraBom)
}

dependencies {
    koraBom platform("io.koraframework:kora-parent:$koraVersion")

    annotationProcessor "io.koraframework:annotation-processors"

    implementation "io.koraframework:database-jdbc"
    implementation "io.koraframework:config-hocon"
    implementation "io.koraframework:json-common"
    implementation "io.koraframework:http-server-undertow"
    implementation "gg.jte:jte:3.2.3"
    implementation "org.postgresql:postgresql:42.7.11"
    implementation "org.slf4j:slf4j-nop:2.0.17"
    implementation("io.undertow:undertow-core") {
        version { strictly("2.3.24.Final") }
    }
    implementation("org.jboss.threads:jboss-threads") {
        version { strictly("3.9.2") }
    }
    implementation("org.jboss.xnio:xnio-nio") {
        version { strictly("3.8.17.Final") }
    }

    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:postgresql:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
}

//noinspection GroovyAssignabilityCheck
run {
    environment([
            "POSTGRES_JDBC_URL": "jdbc:postgresql://localhost:5432/postgres",
            "POSTGRES_USER"    : "postgres",
            "POSTGRES_PASS"    : "postgres",
            "JET_CUSTOM"         : "true",
    ])
}

application {
    applicationName = "application"
    mainClass = "io.koraframework.benchmark.Application"
    applicationDefaultJvmArgs = ["-Dfile.encoding=UTF-8"]
}

distTar {
    archiveFileName = "application.tar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = java.nio.file.Paths.get(projectDir.absolutePath, "build", "generated", "jte")
    sourceSets.main.java.srcDirs += "build/generated/jte"
    contentType = gg.jte.ContentType.Html
}

compileJava.dependsOn tasks.generateJte
