httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  virtualThreadsEnabled = false
  virtualThreadsEnabled = ${?VIRTUAL_THREADS_ENABLED}
  telemetry {
      logging.enabled = false
      metrics.enabled = false
      tracing.enabled = false
  }
}

db {
  connectionUri = ${POSTGRES_VERTX_URI}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  maxPoolSize = 512
  poolName = "kotlin-kora1-vertx-repository-suspend"
  telemetry {
      logging.enabled = false
      metrics.enabled = false
      tracing.enabled = false
  }
}

logging.levels {
  "root": "WARN"
}
