plugins {
    id "org.jetbrains.kotlin.jvm" version "2.4.10"
    id "com.google.devtools.ksp" version "2.3.11"
    id "application"
    id "gg.jte.gradle" version "3.2.3"
}

version = kora2Version

configurations {
    koraBom
    ksp.extendsFrom(koraBom)
    compileOnly.extendsFrom(koraBom)
    implementation.extendsFrom(koraBom)
    testImplementation.extendsFrom(koraBom)
    kspTest.extendsFrom(koraBom)
}

dependencies {
    koraBom platform("io.koraframework:kora-bom:$kora2Version")
    ksp "io.koraframework:symbol-processors"

    implementation "io.koraframework:database-jdbc"
    implementation "io.koraframework:config-hocon"
    implementation "io.koraframework:json-common"
    implementation "io.koraframework:http-server-undertow"
    implementation "gg.jte:jte:3.2.3"
    implementation "org.postgresql:postgresql:42.7.11"

    runtimeOnly "org.slf4j:slf4j-nop:2.0.17"

    testImplementation "org.testcontainers:testcontainers:1.21.4"
    testImplementation "org.testcontainers:postgresql:1.21.4"
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
    testImplementation "org.postgresql:postgresql:42.7.11"
    testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
}

kotlin {
    jvmToolchain(25)
    sourceSets.main.kotlin.srcDir("build/generated/ksp/main/kotlin")
    sourceSets.test.kotlin.srcDir("build/generated/ksp/test/kotlin")
}

ksp {
    arg("kora.app.submodule.enabled", "true")
}

jte {
    generate()
    binaryStaticContent = true
    contentType = gg.jte.ContentType.Html
}

tasks.generateJte {
    sourceDirectory = layout.projectDirectory.dir("src/main/jte").asFile.toPath()
    targetDirectory = layout.buildDirectory.dir("generated/jte").get().asFile.toPath()
    contentType = gg.jte.ContentType.Html
}

sourceSets {
    main {
        java.srcDir(layout.buildDirectory.dir("generated/jte"))
    }
}

compileKotlin.dependsOn tasks.generateJte

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 25
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = "25"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    dependsOn(tasks.named("distTar"))
}

application {
    applicationName = "application"
    mainClass.set("io.techempower.benchmark.kora.ApplicationKt")
    applicationDefaultJvmArgs = ["-Dfile.encoding=UTF-8"]
}

tasks.named("run") {
    environment([
            "POSTGRES_JDBC_URL": "jdbc:postgresql://$postgresHost:$postgresPort/$postgresDatabase",
            "POSTGRES_USER"    : "$postgresUser",
            "POSTGRES_PASS"    : "$postgresPassword",
    ])
}

tasks.named("distTar") {
    archiveFileName = "application.tar"
}
