quarkus.http.port=8080

# Virtual Threads
quarkus.virtual-threads.enabled=${VIRTUAL_THREADS_ENABLED:false}
quarkus.virtual-threads.provider=jdk

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASS:postgres}
quarkus.datasource.jdbc.url=${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
quarkus.datasource.jdbc.max-size=512
quarkus.datasource.jdbc.min-size=16

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.log.level=OFF
quarkus.log.console.enable=false
